version: 0.2

env:
  parameter-store:
    EXEC_ROLE: "AW_VERIFICATION_EMAIL_ROLE"
    FUNCTION_NAME: "AW_VERIFICATION_EMAIL_NAME"

phases: 
  pre_build: 
    commands: 
      - pwd
      - ls
      #- zip SendingEmail.zip sending_email.js
  build: 
    commands: 
      - hostname
      - ls
      - zip Sending_Email.zip sending_email.js
      - aws lambda create-function --function-name $FUNCTION_NAME --runtime nodejs14.x --memory-size 128 --timeout 3 --zip-file "fileb://Sending_Email.zip" --handler $FUNCTION_NAME.handler --role $EXEC_ROLE --region ${DEFAULT_REGION} || aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file "fileb://Sending_Email.zip"  --region ${DEFAULT_REGION}  
