version: 0.2

env:
  parameter-store:
    EXEC_ROLE: "AW_VERIFICATION_EMAIL_ROLE"
    FUNCTION_NAME: "AW_VERIFICATION_EMAIL_NAME"
    SQS_ARN: "AW_SQS_ARN_PREFIX"
  variables:
    HANDLER: "index"
    Q_NAME: "AWVerificationEmailBasicPP"
    ZIP_FILE: "new-function.zip"

phases: 
  pre_build: 
    commands: 
      - pwd
      - ls 
      - aws sqs create-queue --queue-name $Q_NAME    
  build: 
    commands: 
      - hostname
      - ls
      - zip -r $ZIP_FILE src/index.js node_modules/dotenv src/helpers/templateHelper.js src/helpers/emailHelper.js
      #- zip Sending_Email.zip index.js
      - aws lambda create-function --function-name $FUNCTION_NAME --runtime nodejs12.x --memory-size 128 --timeout 10 --zip-file "fileb://$ZIP_FILE" --handler $HANDLER.handler --role $EXEC_ROLE --region $AWS_DEFAULT_REGION || aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file "fileb://$ZIP_FILE" --region $AWS_DEFAULT_REGION
      # create new lambda || update lambda code
      - aws lambda create-event-source-mapping --function-name $FUNCTION_NAME --event-source-arn $SQS_ARN$Q_NAME || echo "trigger alread exists"  
      # create event trigger for lambda || trigger already exists